Repository zenml-io/vscode-zenml, pull requests merged in 2025-03, with the labels that each got.

#92 feat: add spell check workflow and configuration
  .github/workflows/spellcheck.yml
  .typos.toml
  CONTRIBUTING.md
  bundled/tool/zenml_wrappers.py
  scripts/spellcheck.sh
  src/commands/stack/StackForm.ts
  src/common/panels.ts
  src/services/LSClient.ts
  src/test/python_tests/lsp_test_client/session.py
  src/test/python_tests/lsp_test_client/utils.py
  src/test/python_tests/requirements.in
Labels: enhancement, CI

#108 Fix stack registration & DAG rendering with UI enhancements for ZenML v0.75.0
  README.md
  bundled/tool/constants.py
  bundled/tool/lazy_import.py
  bundled/tool/lsp_jsonrpc.py
  bundled/tool/lsp_zenml.py
  bundled/tool/type_hints.py
  bundled/tool/zen_watcher.py
  bundled/tool/zenml_client.py
  bundled/tool/zenml_grapher.py
  bundled/tool/zenml_wrappers.py
  resources/dag-view/dag.css
  src/commands/components/cmds.ts
  src/commands/components/registry.ts
  src/commands/pipelines/DagRender.ts
  src/commands/stack/StackForm.ts
  src/commands/stack/cmds.ts
  src/test/ts_tests/__mocks__/constants.ts
  src/types/StackTypes.ts
  src/utils/componentUtils.ts
  src/utils/constants.ts
  src/views/activityBar/common/PaginatedDataProvider.ts
  src/views/activityBar/common/TreeItemWithChildren.ts
  src/views/activityBar/componentView/ComponentDataProvider.ts
  src/views/activityBar/componentView/ComponentTreeItems.ts
  src/views/activityBar/stackView/StackDataProvider.ts
  src/views/activityBar/stackView/StackTreeItems.ts
Labels: enhancement

#111 Migrate to Ruff for Python formatting and linting
  .github/dependabot.yml
  .vscode/settings.json
  CONTRIBUTING.md
  bundled/tool/lsp_jsonrpc.py
  bundled/tool/lsp_server.py
  bundled/tool/lsp_utils.py
  bundled/tool/lsp_zenml.py
  bundled/tool/zen_watcher.py
  bundled/tool/zenml_wrappers.py
  noxfile.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  scripts/format.sh
  scripts/lint.sh
  src/test/python_tests/requirements.txt
Labels: CI, dependencies

#109 Bump dependencies to resolve Dependabot alerts
  .eslintrc.json
  package-lock.json
  package.json
Labels: dependencies

#121 Dependencies Update
  package-lock.json
  package.json
  src/views/activityBar/environmentView/EnvironmentItem.ts
Labels: CI

#133 UI Improvements and Project/Stack Management Refactor
  CHANGELOG.md
  README.md
  package.json
  package.nls.json
  resources/zenml-extension-new.gif
  src/commands/projects/cmds.ts
  src/commands/projects/registry.ts
  src/commands/stack/cmds.ts
  src/commands/stack/registry.ts
  src/commands/stack/utils.ts
  src/extension.ts
  src/services/LSClient.ts
  src/test/ts_tests/commands/projectCommands.test.ts
  src/test/ts_tests/commands/stackCommands.test.ts
  src/utils/constants.ts
  src/utils/refresh.ts
  src/utils/ui-constants.ts
  src/views/activityBar/componentView/ComponentTreeItems.ts
  src/views/activityBar/pipelineView/PipelineDataProvider.ts
  src/views/activityBar/pipelineView/PipelineTreeItems.ts
  src/views/activityBar/projectView/ProjectDataProvider.ts
  src/views/activityBar/projectView/ProjectTreeItems.ts
  src/views/activityBar/serverView/ServerDataProvider.ts
  src/views/activityBar/serverView/ServerTreeItems.ts
  src/views/activityBar/stackView/StackDataProvider.ts
  src/views/activityBar/stackView/StackTreeItems.ts
  src/views/statusBar/index.ts
Labels: enhancement

#134 Improve Extension Stability and User Experience
  CHANGELOG.md
  README.md
  VERSIONS.md
  bundled/tool/zenml_wrappers.py
  src/commands/projects/utils.ts
  src/commands/stack/utils.ts
  src/types/LSClientResponseTypes.ts
  src/utils/constants.ts
  src/utils/ui-constants.ts
  src/views/activityBar/componentView/ComponentDataProvider.ts
  src/views/activityBar/stackView/StackDataProvider.ts
  src/views/statusBar/index.ts
Labels: enhancement
